"use client";
import Nav from "@/components/Nav";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import CartProvider from "@/contexts/Cart";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<SessionProvider>
				<CartProvider>
					<body>
						<Nav />
						{children}
					</body>
				</CartProvider>
			</SessionProvider>
		</html>
	);
}
